//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_Locations
    {
        public Appointment_Locations()
        {
            this.Appointments_Master = new HashSet<Appointments_Master>();
        }
    
        public int Appointment_Location_ID { get; set; }
        public string Appointment_Location_Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Appointments_Master> Appointments_Master { get; set; }
    }
}
