//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments_Master
    {
        public int Appointment_Request_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Dietitian_ID { get; set; }
        public Nullable<System.DateTime> Requested_DateTime { get; set; }
        public string Request_Comments { get; set; }
        public Nullable<int> Request_Location { get; set; }
        public Nullable<int> Request_Status { get; set; }
    
        public virtual Appointment_Locations Appointment_Locations { get; set; }
        public virtual Dietitian Dietitian { get; set; }
    }
}
