//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Blog_ID { get; set; }
        public string Blog_Title { get; set; }
        public Nullable<System.DateTime> Blog_Date { get; set; }
        public string Blog_Author { get; set; }
        public string Blog_Body { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
