//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dietitian
    {
        public Dietitian()
        {
            this.Appointments_Master = new HashSet<Appointments_Master>();
        }
    
        public int Dietian_ID { get; set; }
        public string FullName { get; set; }
        public string NPI { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Appointments_Master> Appointments_Master { get; set; }
    }
}
