//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NutritionDBEntities : DbContext
    {
        public NutritionDBEntities()
            : base("name=NutritionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment_Locations> Appointment_Locations { get; set; }
        public virtual DbSet<Appointments_Master> Appointments_Master { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Dietitian> Dietitians { get; set; }
        public virtual DbSet<HourSlot> HourSlots { get; set; }
        public virtual DbSet<Initial_Assessment> Initial_Assessment { get; set; }
        public virtual DbSet<LabData> LabDatas { get; set; }
        public virtual DbSet<ListZip> ListZips { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Patient_Record_Assessment> Patient_Record_Assessment { get; set; }
        public virtual DbSet<PatientDailyMenu> PatientDailyMenus { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<v_UserAccounts> v_UserAccounts { get; set; }
    }
}
