//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Record_Assessment
    {
        public int Patient_Record_Assessment_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<bool> Hx_Anemia { get; set; }
        public Nullable<bool> Hx_Cancer { get; set; }
        public string Hx_Cancer_Description { get; set; }
        public Nullable<bool> Hx_Anorexia { get; set; }
        public Nullable<bool> Hx_Cardiovascular { get; set; }
        public string Hx_Cardiovascular_Description { get; set; }
        public Nullable<bool> Hx_Bulimia { get; set; }
        public Nullable<bool> Hx_Gastro { get; set; }
        public string Hx_Gastro_Description { get; set; }
        public Nullable<bool> Hx_Artritis { get; set; }
        public Nullable<bool> Hx_Renal { get; set; }
        public string Hx_Renal_Description { get; set; }
        public Nullable<bool> Hx_Depresion { get; set; }
        public Nullable<bool> Hx_Hipoglucemia { get; set; }
        public Nullable<bool> Hx_Diabetes { get; set; }
        public Nullable<bool> Hx_Hipotension { get; set; }
        public Nullable<bool> Hx_Epilepsia { get; set; }
        public Nullable<bool> Hx_Mareos { get; set; }
        public Nullable<bool> Hx_Higado { get; set; }
        public Nullable<bool> Hx_Migrane { get; set; }
        public Nullable<bool> Hx_Hipercolesterolemia { get; set; }
        public Nullable<bool> Hx_Tiroide { get; set; }
        public Nullable<bool> Hx_Hiperlipidemia { get; set; }
        public Nullable<bool> Hx_Vertigo { get; set; }
        public Nullable<bool> Hx_Hipertension { get; set; }
        public Nullable<bool> Hx_Other { get; set; }
        public string Hx_Other_Description { get; set; }
        public string Cirujias_1 { get; set; }
        public Nullable<System.DateTime> Cirujias_1_Date { get; set; }
        public string Cirujias_2 { get; set; }
        public Nullable<System.DateTime> Cirujias_2_Date { get; set; }
        public string Cirujias_3 { get; set; }
        public Nullable<System.DateTime> Cirujias_3_Date { get; set; }
        public string Drug_List { get; set; }
        public string Supplements_List { get; set; }
        public string Alergic_To_Drugs { get; set; }
        public string Allergic_To_Food { get; set; }
        public Nullable<bool> Fx_Anemia { get; set; }
        public Nullable<bool> Fx_Gastro { get; set; }
        public string Fx_Gastro_Description { get; set; }
        public Nullable<bool> Fx_Anorexia { get; set; }
        public Nullable<bool> Fx_Renal { get; set; }
        public string Fx_Renal_Description { get; set; }
        public Nullable<bool> Fx_Bulimia { get; set; }
        public Nullable<bool> Fx_Respiratory { get; set; }
        public string Fx_Respiratory_Description { get; set; }
        public Nullable<bool> Fx_Artritis { get; set; }
        public Nullable<bool> Fx_Depresion { get; set; }
        public Nullable<bool> Fx_Cancer { get; set; }
        public string Fx_Cancer_Description { get; set; }
        public Nullable<bool> Fx_Epilepsia { get; set; }
        public Nullable<bool> Fx_Cardiovascular { get; set; }
        public string Fx_Cardiovascular_Description { get; set; }
        public Nullable<bool> Fx_Higado { get; set; }
        public Nullable<bool> Fx_Hipercolesterolemimia { get; set; }
        public Nullable<bool> Fx_Mareos { get; set; }
        public Nullable<bool> Fx_Hiperlipidemias { get; set; }
        public Nullable<bool> Fx_Migrane { get; set; }
        public Nullable<bool> Fx_Hipertension { get; set; }
        public Nullable<bool> Fx_Tiroide { get; set; }
        public Nullable<bool> Fx_Hipoglucemia { get; set; }
        public Nullable<bool> Fx_Vertigo { get; set; }
        public Nullable<bool> Fx_Hipotension { get; set; }
        public Nullable<bool> Fx_Other { get; set; }
        public string Fx_Other_Description { get; set; }
        public Nullable<int> Meals_Per_Day { get; set; }
        public Nullable<int> Snacks_Per_Day { get; set; }
        public Nullable<int> Eat_Outside_Breakfast_Count { get; set; }
        public Nullable<int> Eat_Outside_Lunch_Count { get; set; }
        public Nullable<int> Eat_Outside_Dinner_Count { get; set; }
        public Nullable<int> Eat_Outside_Place { get; set; }
        public string Eat_Outside_Place_Other { get; set; }
        public Nullable<int> Fruits_Per_Day { get; set; }
        public Nullable<int> Fruit_Juice_Per_Day { get; set; }
        public Nullable<int> Vegetables_Per_Day { get; set; }
        public Nullable<int> Poultry_Per_Day { get; set; }
        public Nullable<int> Fish_Per_Day { get; set; }
        public Nullable<int> Red_Meat_Per_Day { get; set; }
        public Nullable<int> Seafood_Per_Day { get; set; }
        public Nullable<int> Water_Per_Day { get; set; }
        public Nullable<int> Milk_Whole_Per_Day { get; set; }
        public Nullable<int> Milk_Low_Fat_Per_Day { get; set; }
        public Nullable<int> Juice_Per_Day { get; set; }
        public Nullable<int> Milk_No_Fat_Per_Day { get; set; }
        public Nullable<int> Soda_Per_Day { get; set; }
        public Nullable<int> Diet_Soda_Per_Day { get; set; }
        public Nullable<int> Beer_Per_Day { get; set; }
        public Nullable<int> Tea_Per_Day { get; set; }
        public Nullable<int> Wine_Per_Day { get; set; }
        public Nullable<int> Tea_Sugar_Per_Day { get; set; }
        public Nullable<int> Licor_Per_Day { get; set; }
        public Nullable<int> Power_Drinks_Per_Day { get; set; }
        public string Reason_For_Service { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
