//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
        }
    
        public int UserAccount_ID { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Role Role { get; set; }
    }
}
