//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carolyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_Requests
    {
        public int Appointment_Request_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<System.DateTime> Requested_DateTime { get; set; }
        public Nullable<int> Request_Status { get; set; }
    }
}
