//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carolyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Initial_Assessment
    {
        public int Initial_Assessment_ID { get; set; }
        public string Problems { get; set; }
        public string Apetite { get; set; }
        public Nullable<bool> Nausea { get; set; }
        public Nullable<bool> Diarrea { get; set; }
        public Nullable<bool> Vomit { get; set; }
        public Nullable<bool> Constipation { get; set; }
        public Nullable<bool> ChewingProblems { get; set; }
        public Nullable<bool> SwallowingProblems { get; set; }
        public Nullable<bool> ChangeInTaste { get; set; }
        public Nullable<bool> FoodAllergies { get; set; }
        public Nullable<bool> LactoseIntolerance { get; set; }
        public string Barriers { get; set; }
        public Nullable<bool> PhysicalActivity { get; set; }
        public string PhysicalActivity_Details { get; set; }
        public Nullable<bool> ChangeInWeight { get; set; }
        public string DrugsList { get; set; }
        public string SupplementsList { get; set; }
        public string CurrentDiet { get; set; }
        public Nullable<int> Height_Centimeters { get; set; }
        public string Bone_Structure { get; set; }
        public Nullable<int> ABW { get; set; }
        public Nullable<int> UBW { get; set; }
        public Nullable<int> IBW { get; set; }
        public Nullable<decimal> BMI { get; set; }
        public Nullable<int> UBWP { get; set; }
        public Nullable<int> IBWP { get; set; }
        public string TasteAndPreferences { get; set; }
    }
}
