//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carolyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabData
    {
        public int LabData_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<decimal> Hemoglobin { get; set; }
        public Nullable<decimal> HematocritP { get; set; }
        public Nullable<decimal> MCV { get; set; }
        public Nullable<decimal> MCHC { get; set; }
        public Nullable<decimal> TLC { get; set; }
        public Nullable<decimal> Glucose { get; set; }
        public Nullable<decimal> BUN { get; set; }
        public Nullable<decimal> Creatinine { get; set; }
        public Nullable<decimal> ProteinTotal { get; set; }
        public Nullable<decimal> Albumin { get; set; }
        public Nullable<decimal> ColesterolTotal { get; set; }
        public Nullable<decimal> ColesterolLDL { get; set; }
        public Nullable<decimal> ColesterolHDL { get; set; }
        public Nullable<decimal> Triglicerides { get; set; }
        public Nullable<decimal> Sodium { get; set; }
        public Nullable<decimal> AST { get; set; }
        public Nullable<decimal> ALT { get; set; }
        public Nullable<decimal> ALKP { get; set; }
        public string Other { get; set; }
    }
}
