//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carolyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Patient_Record_Assessment = new HashSet<Patient_Record_Assessment>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int Patient_ID { get; set; }
        public string Full_Name { get; set; }
        public Nullable<System.DateTime> Record_Date { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Res_Address_Line_1 { get; set; }
        public string Res_Address_Line_2 { get; set; }
        public string Res_Town { get; set; }
        public string Res_ZipCode { get; set; }
        public string Main_Phone { get; set; }
        public string Other_Phone { get; set; }
        public string Email { get; set; }
        public string Job { get; set; }
        public string Work_Phone { get; set; }
        public string Emergency_Contact { get; set; }
        public string Emergency_Contact_Relationship { get; set; }
        public string Emergency_Contact_Phone { get; set; }
    
        public virtual ICollection<Patient_Record_Assessment> Patient_Record_Assessment { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
