//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carolyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDailyMenu
    {
        public int DailyMenu_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<System.DateTime> DailyMenuEntryDate { get; set; }
        public Nullable<int> Portion { get; set; }
        public string Food { get; set; }
        public string CategoryGroup { get; set; }
    }
}
