//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carolyn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int Role_ID { get; set; }
        public string Role_Description { get; set; }
    
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
